import type { ParadeVehicle } from './types'

export const mockVehicles: ParadeVehicle[] = [
  {
    id: 1,
    name: "L'Envol de Neverland",
    universe: 'Peter Pan',
    main_character: 'Peter Pan',
    position: 1,
    status: 'ready',
    has_night_lighting: true,
    image_url: 'https://images.unsplash.com/photo-1551029506-0807df4e2031?auto=format&fit=crop&w=900&q=85',
    notes: 'Le véhicule simule un vol au-dessus de Londres.',
  },
  {
    id: 2,
    name: 'Le Royaume des Glaces',
    universe: 'La Reine des Neiges',
    main_character: 'Elsa',
    position: 2,
    status: 'preparing',
    has_night_lighting: true,
    image_url: 'https://images.unsplash.com/photo-1484950763426-56b5bf172dbb?auto=format&fit=crop&w=900&q=85',
    notes: 'Prévoir le test des effets de neige avant la répétition générale.',
  },
  {
    id: 3,
    name: 'La Savane en Fête',
    universe: 'Le Roi Lion',
    main_character: 'Simba',
    position: 3,
    status: 'maintenance',
    has_night_lighting: false,
    image_url: 'https://images.unsplash.com/photo-1518709594023-6eab9bab7b23?auto=format&fit=crop&w=900&q=85',
    notes: 'Un contrôle du mécanisme principal est nécessaire.',
  },
  {
    id: 4,
    name: "Les Aventures d'Agrabah",
    universe: 'Aladdin',
    main_character: 'Aladdin',
    position: 4,
    status: 'ready',
    has_night_lighting: true,
    image_url: 'https://images.unsplash.com/photo-1539650116574-75c0c6d73f6e?auto=format&fit=crop&w=900&q=85',
    notes: 'Le tapis volant est installé et prêt pour le défilé.',
  },
  {
    id: 5,
    name: 'Toy Story en Tournée',
    universe: 'Toy Story',
    main_character: 'Woody',
    position: 5,
    status: 'ready',
    has_night_lighting: true,
    image_url: 'https://images.unsplash.com/photo-1566576912321-d58ddd7a6088?auto=format&fit=crop&w=900&q=85',
    notes: 'Vérifier la hauteur des accessoires avant le départ.',
  },
  {
    id: 6,
    name: 'La Fête des Océans',
    universe: 'Vaiana',
    main_character: 'Vaiana',
    position: 6,
    status: 'preparing',
    has_night_lighting: true,
    image_url: 'https://images.unsplash.com/photo-1510414842594-a61c69b5ae57?auto=format&fit=crop&w=900&q=85',
    notes: 'La voile principale est en cours de finition.',
  },
]
